const keyboardLayout = [
  [
    { en: '`', ru: 'ё', width: 'regular' },
    { en: '1', ru: '1', width: 'regular' },
    { en: '2', ru: '2', width: 'regular' },
    { en: '3', ru: '3', width: 'regular' },
    { en: '4', ru: '4', width: 'regular' },
    { en: '5', ru: '5', width: 'regular' },
    { en: '6', ru: '6', width: 'regular' },
    { en: '7', ru: '7', width: 'regular' },
    { en: '8', ru: '8', width: 'regular' },
    { en: '9', ru: '9', width: 'regular' },
    { en: '0', ru: '0', width: 'regular' },
    { en: '-', ru: '-', width: 'regular' },
    { en: '=', ru: '=', width: 'regular' },
    { en: '⌫ Back', ru: '⌫ Back', width: 'wide' },
    { en: 'Del ⌦', ru: 'Del ⌦', width: 'wide' },
  ],
  [
    { en: '↹ Tab', ru: '↹ Tab', width: 'extra-wide' },
    { en: 'q', ru: 'й', width: 'regular' },
    { en: 'w', ru: 'ц', width: 'regular' },
    { en: 'e', ru: 'у', width: 'regular' },
    { en: 'r', ru: 'к', width: 'regular' },
    { en: 't', ru: 'е', width: 'regular' },
    { en: 'y', ru: 'н', width: 'regular' },
    { en: 'u', ru: 'г', width: 'regular' },
    { en: 'i', ru: 'ш', width: 'regular' },
    { en: 'o', ru: 'щ', width: 'regular' },
    { en: 'p', ru: 'з', width: 'regular' },
    { en: '[', ru: 'х', width: 'regular' },
    { en: ']', ru: 'ъ', width: 'regular' },
    { en: '\\', ru: '\\', width: 'regular' },
  ],
  [
    { en: '🅰 Caps', ru: '🅰 Caps', width: 'extra-wide' },
    { en: 'a', ru: 'ф', width: 'regular' },
    { en: 's', ru: 'ы', width: 'regular' },
    { en: 'd', ru: 'в', width: 'regular' },
    { en: 'f', ru: 'а', width: 'regular' },
    { en: 'g', ru: 'п', width: 'regular' },
    { en: 'h', ru: 'р', width: 'regular' },
    { en: 'j', ru: 'о', width: 'regular' },
    { en: 'k', ru: 'л', width: 'regular' },
    { en: 'l', ru: 'д', width: 'regular' },
    { en: ';', ru: 'ж', width: 'regular' },
    { en: "'", ru: 'э', width: 'regular' },
    { en: '↩ Enter', ru: '↩ Enter', width: 'extra-wide' },
  ],
  [
    { en: '⇧ Shift', ru: '⇧ Shift', width: 'extra-wide' },
    { en: 'z', ru: 'я', width: 'regular' },
    { en: 'x', ru: 'ч', width: 'regular' },
    { en: 'c', ru: 'с', width: 'regular' },
    { en: 'v', ru: 'м', width: 'regular' },
    { en: 'b', ru: 'и', width: 'regular' },
    { en: 'n', ru: 'т', width: 'regular' },
    { en: 'm', ru: 'ь', width: 'regular' },
    { en: ',', ru: 'б', width: 'regular' },
    { en: '.', ru: 'ю', width: 'regular' },
    { en: '/', ru: '.', width: 'regular' },
    { en: '⯅', ru: '⯅', width: 'regular' },
    { en: '⇧ Shift', ru: '⇧ Shift', width: 'extra-wide' },
  ],
  [
    { en: 'Ctrl', ru: 'Ctrl', width: 'wide' },
    { en: 'Alt', ru: 'Alt', width: 'regular' },
    { en: '', ru: '', width: 'ultra-wide' },
    { en: 'Alt', ru: 'Alt', width: 'regular' },
    { en: 'Ctrl', ru: 'Ctrl', width: 'wide' },
    { en: '⯇', ru: '⯇', width: 'regular' },
    { en: '⯆', ru: '⯆', width: 'regular' },
    { en: '⯈', ru: '⯈', width: 'regular' },
  ],
];

export default keyboardLayout;
