[[redirects]]
  from = "https://virtual-keyboard-aleksey-vl-ivanov.netlify.app/*"
  to = "https://virtual-keyboard.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://virtual-keyboard-aleksey-vl-ivanov.netlify.app/*"
  to = "https://virtual-keyboard.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://virtual-keyboard.aleksey-vl-ivanov.com/*"
  to = "https://virtual-keyboard.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true